/**
 * Reality Builder — English option pools.
 * Edit these arrays to add more worlds, rules, characters, problems, and twists.
 */
export const REALITY_BUILDER_OPTIONS_EN = {
  world: [
    "A floating city",
    "An underground hospital",
    "A desert made of mirrors",
    "A forest with electric trees",
    "A train that never stops",
    "A moon-sized library",
    "A canyon painted with thunderstorms",
    "A metropolis built inside a whale’s memory",
    "An island that appears only in fog",
    "A valley where buildings grow like plants",
  ],
  rule: [
    "Time only moves when people sing",
    "Gravity changes every hour",
    "Nobody can lie, but everyone speaks in riddles",
    "Doors lead to memories instead of rooms",
    "Every decision creates a new weather pattern",
    "Machines dream at night",
    "Shadows update faster than the objects that cast them",
    "Water remembers everyone who touches it",
    "Maps only work when you admit you are lost",
    "Silence is heavier than stone",
  ],
  character: [
    "A doctor who repairs broken timelines",
    "A musician who controls storms",
    "A programmer who debugs dreams",
    "A child who remembers the future",
    "A robot that collects forgotten words",
    "A gardener who grows planets",
    "An archivist who files emotions by scent",
    "A courier who delivers messages to past selves",
    "A lighthouse keeper for collapsing dimensions",
    "A detective who interviews echoes",
  ],
  problem: [
    "The sun forgot how to rise",
    "The city is slowly turning invisible",
    "Everyone lost the ability to ask questions",
    "The hospital keeps generating new rooms",
    "The ocean started speaking in code",
    "Dreams are leaking into the streets",
    "Clocks argue about what “now” means",
    "Forgotten names are filling the sky like smoke",
    "The horizon keeps shrinking every dawn",
    "The archives began rewriting themselves overnight",
  ],
  twist: [
    "The villain is actually the narrator",
    "The solution is hidden inside a song",
    "The character must delete one memory to save the world",
    "The map is alive and keeps changing",
    "The problem was created by a previous version of the user",
    "The ending changes every time someone reads it",
    "The world resets whenever someone apologizes sincerely",
    "The twist was revealed in the first sentence — nobody noticed",
    "The cure is indistinguishable from the curse",
    "The exit only opens when you stop looking for it",
  ],
} as const;
