/**
 * Reality Builder — pools en español (editá aquí para sumar más opciones).
 */
export const REALITY_BUILDER_OPTIONS_ES = {
  world: [
    "Una ciudad flotante",
    "Un hospital subterráneo",
    "Un desierto hecho de espejos",
    "Un bosque con árboles eléctricos",
    "Un tren que nunca se detiene",
    "Una biblioteca del tamaño de la luna",
    "Un cañón pintado con tormentas",
    "Una metrópolis construida dentro de la memoria de una ballena",
    "Una isla que solo aparece con niebla",
    "Un valle donde los edificios crecen como plantas",
  ],
  rule: [
    "El tiempo solo avanza cuando la gente canta",
    "La gravedad cambia cada hora",
    "Nadie puede mentir, pero todos hablan en acertijos",
    "Las puertas llevan a recuerdos en vez de habitaciones",
    "Cada decisión crea un nuevo clima",
    "Las máquinas sueñan de noche",
    "Las sombras se actualizan más rápido que los objetos",
    "El agua recuerda a quien la toca",
    "Los mapas solo funcionan si admitís que te perdiste",
    "El silencio pesa más que la piedra",
  ],
  character: [
    "Un médico que repara líneas de tiempo rotas",
    "Un músico que controla tormentas",
    "Un programador que depura sueños",
    "Un niño que recuerda el futuro",
    "Un robot que colecciona palabras olvidadas",
    "Un jardinero que cultiva planetas",
    "Un archivista que clasifica emociones por olor",
    "Un mensajero que entrega cartas a versiones pasadas de uno mismo",
    "Un farero de dimensiones que se derrumban",
    "Un detective que interroga a los ecos",
  ],
  problem: [
    "El sol olvidó cómo salir",
    "La ciudad se vuelve invisible lentamente",
    "Todos perdieron la capacidad de preguntar",
    "El hospital sigue generando habitaciones nuevas",
    "El océano empezó a hablar en código",
    "Los sueños se filtran a las calles",
    "Los relojes discuten qué es el “ahora”",
    "Nombres olvidados llenan el cielo como humo",
    "El horizonte se encoge con cada amanecer",
    "Los archivos se reescriben solos de noche",
  ],
  twist: [
    "El villano en realidad es el narrador",
    "La solución está escondida en una canción",
    "El personaje debe borrar un recuerdo para salvar el mundo",
    "El mapa está vivo y no deja de cambiar",
    "El problema lo creó una versión anterior del usuario",
    "El final cambia cada vez que alguien lo lee",
    "El mundo se reinicia cuando alguien pide disculpas de verdad",
    "El giro se dijo en la primera frase y nadie lo notó",
    "La cura es indistinguible de la maldición",
    "La salida solo se abre cuando dejás de buscarla",
  ],
} as const;
